import * as generated from './generated';
export * from './generated';

import { OpenAPI } from './generated';

OpenAPI.TOKEN =
  'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNvZ25pdG9Mb2NhbCJ9.eyJhdXRoX3RpbWUiOjE2NzgyMTIwMjMsImNsaWVudF9pZCI6IjljZWhsaTYycXhta2k5bWc1YWRqbXVjdXEiLCJldmVudF9pZCI6IjczNjNiNmU2LThjZDAtNDE5NC1iYTZhLTNjNTkwNWNiY2JjZiIsImlhdCI6MTY3ODIxMjAyMywianRpIjoiNDk1NzM4ZDAtNjZlOC00MGY4LThlNzctYjk5NWEwOTE4NzE1Iiwic2NvcGUiOiJhd3MuY29nbml0by5zaWduaW4udXNlci5hZG1pbiIsInN1YiI6ImM0NDNhZjM3LTJlYWItNDQ2NS1hYzk0LTdlYzhiODE0YWJhZCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInVzZXJuYW1lIjoidGVzdC11c2VyIiwiZXhwIjoxNjc4Mjk4NDIzLCJpc3MiOiJodHRwczovL2NvZ25pdG8taWRwLnVzLXdlc3QtMi5hbWF6b25hd3MuY29tL3VzLXdlc3QtMl9oMjNUSmpRUjkifQ.X-Q7VH1_OCFOl1xYi43Sen8Bjft80_FikETeArCKmrivb47L0R1JE_liBWb0o7r-kaoxx-TCcoai2DLubdvSwyWmHg_Wzjn9MPJqvrEfNRbxyYgceP-ap_ev8zmwsHFpJOkpBUGH6aiVTw1gygLAlysMY8hjSv7YK0cTwkLCJnA9vybsjttA2elog8rhaPOhNUzbQyNQ4S8VvkBR7vF3SqZJr9voAqPLKzSRiJY2Cq4gj3065v-AHJ0X9aT4U7C4EWlTkA3Gvr9sKuCQ_XuIjbZeprHYYPPXaqc27_AuBU55iai13f-kmiJOyd0ElCTIk-wMEcqcR4i_o8a0YHq8DA';
OpenAPI.BASE = 'http://localhost:3000';
export const {
  dashboardsControllerList: listDashboards,
  dashboardsControllerCreate: createDashboard,
  dashboardsControllerRead: readDashboard,
  dashboardsControllerUpdate: updateDashboard,
  dashboardsControllerDelete: deleteDashboard,
} = generated.DashboardsService;
