import * as generated from './generated';
export * from './generated';

import { OpenAPI } from './generated';

OpenAPI.TOKEN =
  'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNvZ25pdG9Mb2NhbCJ9.eyJhdXRoX3RpbWUiOjE2NzgyOTk0NjgsImNsaWVudF9pZCI6IjljZWhsaTYycXhta2k5bWc1YWRqbXVjdXEiLCJldmVudF9pZCI6IjMyNGVlMzBmLWM3NzMtNDVjMS05OTAyLTgxNWU4NjQ3YTNiYyIsImlhdCI6MTY3ODI5OTQ2OCwianRpIjoiODllMGRlYmEtODljYS00NmUyLWI1ODgtZmNmYWI1ZWUzM2MzIiwic2NvcGUiOiJhd3MuY29nbml0by5zaWduaW4udXNlci5hZG1pbiIsInN1YiI6ImM0NDNhZjM3LTJlYWItNDQ2NS1hYzk0LTdlYzhiODE0YWJhZCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInVzZXJuYW1lIjoidGVzdC11c2VyIiwiZXhwIjoxNjc4Mzg1ODY4LCJpc3MiOiJodHRwczovL2NvZ25pdG8taWRwLnVzLXdlc3QtMi5hbWF6b25hd3MuY29tL3VzLXdlc3QtMl9oMjNUSmpRUjkifQ.FemB4Mzg5oenYHSZnkuOeMYIAAlzCg6INiY53nIxHbML3PbziCvs9N-bdrsHxm7dvWNDnYxXpFpztejWbdMchsmUsbZ6-qeLS1OHg2MP-j5wpv4SJfScDx59pO2i00OOyLAfjtne-gfC3KL154wrDoAXTGkoERTLM1uJbOy-Qvn_NrOuttCHl1Dmv7B9laVFvqKjAhv9wf7pLdEAj3yWWdr3MwkEGTcIuOaPgF27Yyp40IfuXDKlbBJbmISRYtkdOSsCUDBqLHF2zUOSVoxhaM7MEzdaJ7HO-R9ZAaHNXoRIhwlZdVvQk9SO_NQU6YgONvF7vxEva7L_pOLdFbbi2w';
OpenAPI.BASE = 'http://localhost:3000';
export const {
  dashboardsControllerList: listDashboards,
  dashboardsControllerCreate: createDashboard,
  dashboardsControllerRead: readDashboard,
  dashboardsControllerUpdate: updateDashboard,
  dashboardsControllerDelete: deleteDashboard,
} = generated.DashboardsService;
